DEF NUM_PLAYER_NAMES EQU 3

IF DEF(_GOLD)
DEF PLAYERNAME1 EQUS "GOLD"
DEF PLAYERNAME2 EQUS "SATOSHI"
DEF PLAYERNAME3 EQUS "JACK"

DEF RIVALNAME1 EQUS "SILVER"
DEF RIVALNAME2 EQUS "SHIGERU"
DEF RIVALNAME3 EQUS "JOHN"
ENDC

IF DEF(_SILVER)
DEF PLAYERNAME1 EQUS "SILVER"
DEF PLAYERNAME2 EQUS "SHIGERU"
DEF PLAYERNAME3 EQUS "JOHN"

DEF RIVALNAME1 EQUS "GOLD"
DEF RIVALNAME2 EQUS "SATOSHI"
DEF RIVALNAME3 EQUS "JACK"
ENDC

DEF MOMNAME1 EQUS "MOM"
DEF MOMNAME2 EQUS "MAMA"
DEF MOMNAME3 EQUS "MOMMY"
