# Newcomer Pokémon (demo dex 152-251), data compiled from The Cutting Room Floor's
# Spaceworld 1997 Demo Pokémon page. Fields:
#   dex, romaji (demo name romanization), english (official EN name if released else "—"),
#   literal (literal translation / etymology for the demo name),
#   typ (demo typing), final (final Pokémon it became, "" if scrapped), status
# status: "kept" identical-ish name, "renamed" released but name changed, "scrapped" never released
NEWCOMERS = [
 (152,"Happa","Chikorita","“leaf” (葉っぱ happa)","Grass","Chikorita (#152)","renamed"),
 (153,"Hanamogura","Bayleef","“flower-mole” (花 hana + 土竜 mogura; moles are “earth dragons” in Japanese)","Grass","Bayleef (#153)","renamed"),
 (154,"Hanaryū","Meganium","“flower-dragon” (花 hana + 竜 ryū)","Grass","Meganium (#154)","renamed"),
 (155,"Honōguma","—","“flame-bear” (炎 honoo + クマ kuma)","Fire","scrapped — replaced by Cyndaquil","scrapped"),
 (156,"Borubeā","—","“Volbear” — volcano + bear","Fire","scrapped — replaced by Quilava","scrapped"),
 (157,"Dainabea","—","“Dynabear” — dynamite + bear","Fire","scrapped — replaced by Typhlosion","scrapped"),
 (158,"Kurusu","—","“Cruise”","Water","scrapped — replaced by Totodile","scrapped"),
 (159,"Akua","—","“Aqua”","Water","scrapped — replaced by Croconaw","scrapped"),
 (160,"Akueria","—","“Aquaria” — Aquarius / aquarium","Water","scrapped — replaced by Feraligatr","scrapped"),
 (161,"Hōhō","Hoothoot","onomatopoeic owl hoot (final JP name kept)","Flying","Hoothoot (#163)","kept"),
 (162,"Bōbō","Noctowl","corruption of Hoothoot’s name","Flying","Noctowl (#164), later renamed Yorunozuku","renamed"),
 (163,"Pachimee","Mareep","spark (パチパチ) + bleat (メエメエ)","Electric","Mareep (#179), later renamed Mērīpu","renamed"),
 (164,"Mokoko","Flaaffy","(final JP name kept)","Electric","Flaaffy (#180)","kept"),
 (165,"Denryū","Ampharos","“electric dragon” (final JP name kept)","Electric","Ampharos (#181)","kept"),
 (166,"Mikon","—","“three” (三 mi) + fox bark (コンコン)","Water*","scrapped Vulpix pre-evolution (*Fire, likely a 1-byte typo)","scrapped"),
 (167,"Monja","—","unkempt hair (もじゃもじゃ); short for Monjara (Tangela)","Grass","scrapped Tangela pre-evolution","scrapped"),
 (168,"Jaranra","—","corruption of Tangela’s name","Grass","scrapped Tangela evolution","scrapped"),
 (169,"Haneei","Mantine","jump (跳ねる) + wing (羽) + ray (エイ)","Water/Flying","Mantine (#226)","renamed"),
 (170,"Pukū","Qwilfish","puffed-up (ぷくぷく) + puffer fish (フグ)","Water","Qwilfish (#211), later renamed Harīsen","renamed"),
 (171,"Shibirefugu","—","numbness (しびれ) + puffer fish (フグ)","Water","scrapped Qwilfish evolution","scrapped"),
 (172,"Pichu","Pichu","(final JP name kept)","Electric","Pichu (#172)","kept"),
 (173,"Pyi","Cleffa","(final JP name kept)","Normal","Cleffa (#173)","kept"),
 (174,"Pupurin","Igglybuff","(final JP name kept)","Normal","Igglybuff (#174)","kept"),
 (175,"Mizuuo","Quagsire","“lancetfish” (水魚 mizuuo)","Water","Quagsire (#195), later renamed Nuō","renamed"),
 (176,"Neiti","Natu","(final JP name kept)","Flying/Psychic","Natu (#177)","kept"),
 (177,"Neitio","Xatu","(final JP name kept)","Flying/Psychic","Xatu (#178)","kept"),
 (178,"Gyopin","—","goldfish (金魚 kingyo) + lively (ピンピン)","Water","scrapped Goldeen pre-evolution","scrapped"),
 (179,"Marill","Marill","(final JP name kept)","Water","Marill (#183)","kept"),
 (180,"Manbō 1","—","“ocean sunfish” (マンボウ); a placeholder name","Water","scrapped sunfish (evolves into Ikari)","scrapped"),
 (181,"Ikari","—","“anchor” (碇) / “rage” (怒り) — same reading","Water/Steel","scrapped shark","scrapped"),
 (182,"Gurotesu","—","“Grotesque”","Water/Steel","scrapped anglerfish/gulper-eel","scrapped"),
 (183,"Ekushingu","Crobat","“X-ing”","Poison/Flying","Crobat (#169)","renamed"),
 (184,"Para","—","“Parasite”; short for Parasu (Paras)","Bug","scrapped Paras pre-evolution","scrapped"),
 (185,"Kokumo","Spinarak","child (子 ko) + spider (クモ kumo)","Bug/Poison","Spinarak (#167), later renamed Itomaru","renamed"),
 (186,"Tsūheddo","Ariados","“Two-headed”","Bug/Poison","Ariados (#168)","renamed"),
 (187,"Yoroidori","Skarmory","armor (鎧 yoroi) + bird (鳥 tori)","Flying/Steel","Skarmory (#227), later renamed Eāmudo","renamed"),
 (188,"Animon","—","animal/anamorph + Metamon (Ditto)","Normal","scrapped Ditto evolution","scrapped"),
 (189,"Hināzu","—","chick (ヒナ hina)","Normal/Flying","scrapped Doduo pre-evolution","scrapped"),
 (190,"Sanī","Sunflora","“Sunny”","Grass/Psychic","Sunflora (#192), later renamed Kimawari","renamed"),
 (191,"Paon","Phanpy","elephant trumpet (パオーン)","Ground","Phanpy (#231), later renamed Gomazō","renamed"),
 (192,"Donfan","Donphan","(final JP name kept)","Ground","Donphan (#232)","kept"),
 (193,"Tsuinzu","Wobbuffet","“Twins” — a scrapped Girafarig pre-evolution, later reworked into Wobbuffet","Dark/Normal","Wobbuffet (#202)","renamed"),
 (194,"Kirinriki","Girafarig","(final JP name kept; palindrome)","Dark/Normal","Girafarig (#203), typing later Psychic/Normal","kept"),
 (195,"Peintā","Smeargle","“Painter”","Normal","Smeargle (#235), later renamed Dōburu","renamed"),
 (196,"Kōnya","—","coin + child (子 ko) + meow (にゃー)","Normal","scrapped Meowth pre-evolution","scrapped"),
 (197,"Rinrin","—","ring + bell-ring (リンリン)","Dark","scrapped bell-themed cat","scrapped"),
 (198,"Berurun","—","bell + cheerful humming (ルンルン)","Dark","scrapped bell-themed cat evolution","scrapped"),
 (199,"Nyorotono","Politoed","(final JP name kept)","Water","Politoed (#186)","kept"),
 (200,"Yadokingu","Slowking","(final JP name kept)","Water/Psychic","Slowking (#199)","kept"),
 (201,"Unown","Unown","(final JP name kept)","Normal","Unown (#201), typing later Psychic","kept"),
 (202,"Ledyba","Ledyba","(final JP name kept)","Bug/Flying","Ledyba (#165)","kept"),
 (203,"Mitsuboshi","Ledian","three (三つ mitsu) + spot/star (星 hoshi)","Bug/Flying","Ledian (#166)","renamed"),
 (204,"Puchikōn","—","petit + unicorn","Normal","scrapped Ponyta pre-evolution","scrapped"),
 (205,"Ēfi","Espeon","(final JP name kept)","Psychic","Espeon (#196)","kept"),
 (206,"Burakkī","Umbreon","(final JP name kept)","Poison","Umbreon (#197), typing later Dark","kept"),
 (207,"Tāban","—","“Turban”","Water","scrapped Slowbro-shell Pokémon","scrapped"),
 (208,"Betobebī","—","Betbetā (Grimer) + baby","Poison","scrapped Grimer pre-evolution","scrapped"),
 (209,"Teppōo","Remoraid","(final JP name kept)","Water","Remoraid (#223)","kept"),
 (210,"Okutan","Octillery","(final JP name kept)","Water","Octillery (#224)","kept"),
 (211,"Gongu","Tyrogue","“Gong”","Fighting","Tyrogue (#236), later renamed Barukī","renamed"),
 (212,"Kapoerā","Hitmontop","(final JP name kept; capoeira)","Fighting","Hitmontop (#237)","kept"),
 (213,"Pudi","—","petit (プチ) + poodle + Gaadi (Growlithe)","Fire","scrapped Growlithe pre-evolution","scrapped"),
 (214,"Haneko","Hoppip","leaf (葉 ha) + cat (猫 neko)","Grass/Flying","Hoppip (#187), later renamed Hanekko","renamed"),
 (215,"Poponeko","Skiploom","dandelion (タンポポ) + cat (猫 neko)","Grass/Flying","Skiploom (#188), later renamed Popokko","renamed"),
 (216,"Wataneko","Jumpluff","cotton (綿 wata) + cat (猫 neko)","Grass/Flying","Jumpluff (#189), later renamed Watakko","renamed"),
 (217,"Baririīna","—","barrier + ballerina","Normal","scrapped Mr. Mime pre-evolution","scrapped"),
 (218,"Rippu","Smoochum","“Lip”","Ice","Smoochum (#238), later renamed Muchūru","renamed"),
 (219,"Erebebī","Elekid","“Elebaby”","Electric","Elekid (#239)","renamed"),
 (220,"Bubī","Magby","(final JP name kept)","Fire","Magby (#240)","kept"),
 (221,"Kireihana","Bellossom","(final JP name kept)","Grass/Poison","Bellossom (#182)","kept"),
 (222,"Tsubomitto","—","bud (蕾 tsubomi) + mitt","Grass/Poison","scrapped Weepinbell branch evolution","scrapped"),
 (223,"Miltank","Miltank","(final JP name kept)","Normal","Miltank (#241)","kept"),
 (224,"Bomushikā","—","bomb + sea lion (アシカ) + seeker","Water/Fire","scrapped circus-seal Pokémon","scrapped"),
 (225,"Gifuto","Delibird","“Gift”","Water/Ice","Delibird (#225)","renamed"),
 (226,"Kotora","—","child (子 ko) + tiger (トラ tora)","Electric","scrapped tiger (originally a Gen I concept)","scrapped"),
 (227,"Raitora","—","thunder (雷 rai) + tiger (トラ tora)","Electric","scrapped tiger evolution","scrapped"),
 (228,"Madāmu","—","“Madame”","Normal/Flying","scrapped Farfetch’d evolution","scrapped"),
 (229,"Norowara","—","to be cursed (呪われる) + straw doll (藁人形)","Ghost","scrapped voodoo-bear","scrapped"),
 (230,"Kyonpan","—","jiangshi (キョンシー) + panda","Ghost","scrapped jiangshi-panda","scrapped"),
 (231,"Yamikarasu","Murkrow","(final JP name kept)","Dark/Flying","Murkrow (#198)","kept"),
 (232,"Happī","Blissey","“Happy”","Normal","Blissey (#242), later renamed Happinasu","renamed"),
 (233,"Shizāsu","Scizor","“Scissors”","Bug/Flying","Scizor (#212), renamed Hassamu; typing later Bug/Steel","renamed"),
 (234,"Purakkusu","—","“Plucks”","Bug","scrapped Pinsir evolution","scrapped"),
 (235,"Debiru","Houndour","“Devil”","Fire","Houndour (#228), later renamed Derubiru","renamed"),
 (236,"Herugā","Houndoom","“Hellgar” (final JP name kept)","Fire","Houndoom (#229)","kept"),
 (237,"Urufuman","—","“Wolfman”","Ice","scrapped mimic Pokémon","scrapped"),
 (238,"Wāurufu","—","“Werewolf”","Ice","scrapped mimic evolution","scrapped"),
 (239,"Porygon2","Porygon2","(final JP name kept)","Normal","Porygon2 (#233)","kept"),
 (240,"Nameeru","—","to lick (舐める nameru)","Normal","scrapped Lickitung evolution","scrapped"),
 (241,"Haganēru","Steelix","“steel” (鋼 hagane) (final JP name kept)","Steel","Steelix (#208)","kept"),
 (242,"Kingudora","Kingdra","(final JP name kept)","Water/Dragon","Kingdra (#230)","kept"),
 (243,"Rai","Raikou","“thunder” (雷 rai)","Electric","Raikou (#243) — early canine design","renamed"),
 (244,"En","Entei","“fire/blaze” (炎 en)","Fire","Entei (#244) — early canine design","renamed"),
 (245,"Sui","Suicune","“water” (水 sui)","Water","Suicune (#245)","renamed"),
 (246,"Nyūra","Sneasel","(final JP name kept)","Ice","Sneasel (#215)","kept"),
 (247,"Hōō","Ho-Oh","(final JP name kept)","Fire/Flying","Ho-Oh (#250)","kept"),
 (248,"Togepy","Togepi","(final JP name kept)","Normal","Togepi (#175)","kept"),
 (249,"Burū","Snubbull","(final JP name kept)","Normal","Snubbull (#209)","kept"),
 (250,"Teiru","Aipom","“Tail”","Normal","Aipom (#190), later renamed Eipam","renamed"),
 (251,"Rīfi","—","“Leafy”","Grass","scrapped Grass Eeveelution — name later reused for Leafeon (Gen IV)","scrapped"),
]
