# Engine / battle / menu / system text, keyed by "<basename>.asm:<Label>"
# (with "#n" for repeated labels), matching gen_site.build_system().
# Many strings are fragments the engine concatenates around an inline
# name/number buffer; those are translated as fragments. <USER>/<TARGET>/
# <PLAYER>/<RIVAL> etc. are engine placeholders, kept verbatim.
SYSTEM = {
# ---- core.asm (battle master text) ----------------------------------------
"core.asm:Unused_OutOfSafariBallsText": "Announcement: 'Ding-dong! You've thrown all your SAFARI BALLs!'",
"core.asm:WildPokemonFledText": "The wild",
"core.asm:WildPokemonFledText#2": "fled!",
"core.asm:EnemyPokemonFledText": "The foe's",
"core.asm:EnemyPokemonFledText#2": "fled!",
"core.asm:HurtByPoisonText": "<USER> is hurt by poison!",
"core.asm:HurtByBurnText": "<USER> is hurt by its burn!",
"core.asm:LeechSeedSapsText": "LEECH SEED saps <USER>'s HP!",
"core.asm:HasANightmareText": "<USER> is locked in a nightmare!",
"core.asm:HurtByCurseText": "<USER> is afflicted by the curse!",
"core.asm:SandstormHitsText": "The sandstorm strikes <USER>!",
"core.asm:PerishCountText": "<USER>'s PERISH count fell to",
"core.asm:PerishCountText#2": "!",
"core.asm:BattleText_SafeguardFaded": "The mystical veil that cloaked <USER> disappeared!",
"core.asm:BattleText_RainContinuesToFall": "Rain continues to fall.",
"core.asm:BattleText_TheSunlightIsStrong": "The sunlight is strong.",
"core.asm:BattleText_TheRainStopped": "The rain stopped!",
"core.asm:BattleText_TheSunlightFaded": "The sunlight faded!",
"core.asm:EnemyMonFainted": "The foe's",
"core.asm:EnemyMonFainted#2": "fainted!",
"core.asm:GotMoneyForWinningText": "<PLAYER> got",
"core.asm:GotMoneyForWinningText#2": "yen for winning!",
"core.asm:BattleText_EnemyWasDefeated": "'s",
"core.asm:BattleText_EnemyWasDefeated#2": "— you won the battle!",
"core.asm:RivalLossText": "<RIVAL>: 'Huh? Maybe I should have traded for your Pokémon...'",
"core.asm:FaintedText": "fainted!",
"core.asm:BattleText_UseNextMon": "Use the next Pokémon?",
"core.asm:RivalWinText": "<RIVAL>: 'Yes! Maybe I picked a good Pokémon after all!'",
"core.asm:OutOfUsableMonsText": "<PLAYER> has no Pokémon left to fight! <PLAYER>'s vision went black!",
"core.asm:LostAgainstText": "— lost the battle!",
"core.asm:TrainerAboutToUseText": "'s",
"core.asm:TrainerAboutToUseText#2": "is about to send in",
"core.asm:TrainerAboutToUseText#3": "Will <PLAYER> switch Pokémon too?",
"core.asm:TrainerSentOutText": "'s",
"core.asm:TrainerSentOutText#2": "sent out",
"core.asm:TrainerSentOutText#3": "!",
"core.asm:BattleText_TheresNoWillToBattle": "There's no will to battle!",
"core.asm:BattleText_CantEscape": "Can't escape!",
"core.asm:BattleText_TheresNoEscapeFromTrainerBattle": "No! There's no turning your back mid-battle!",
"core.asm:BattleText_GotAwaySafely": "Got away safely!",
"core.asm:BattleText_UserFledUsingAStringBuffer1": "<TARGET> used its held",
"core.asm:BattleText_UserFledUsingAStringBuffer1#2": "to flee!",
"core.asm:BattleText_UserHurtBySpikes": "<USER> is hurt by SPIKES!",
"core.asm:RecoveredUsingText": "<TARGET> used its held",
"core.asm:RecoveredUsingText#2": "to recover!",
"core.asm:UseItemFailedText": "<USER>'s held",
"core.asm:UseItemFailedText#2": "activated!",
"core.asm:BattleText_ItemsCantBeUsedHere": "Items can't be used here.",
"core.asm:BattleText_MonIsAlreadyOut_0f": "is already out.",
"core.asm:BattleText_MonCantBeRecalled": "can't be recalled!",
"core.asm:.BattleText_TheresNoPPLeftForThisMove": "There's no PP left for this move!",
"core.asm:.BattleText_TheMoveIsDisabled": "The move is DISABLED!",
"core.asm:.Unused_BattleText_MimicWhichMove": "Mimic which move?",
"core.asm:.BattleText_MonHasNoMovesLeft": "has no moves left that it can use!",
"core.asm:.Disabled": "It's DISABLED!",
"core.asm:.Type": "MOVE TYPE",
"core.asm:BattleText_TargetsEncoreEnded": "<TARGET>'s ENCORE ended!",
"core.asm:BoostedExpPointsText": "gained",
"core.asm:.WithExpAllText": "through the EXP.ALL,",
"core.asm:.BoostedExpPointsText": "a boosted number of",
"core.asm:.ExpPointsText": "EXP. Points!",
"core.asm:GrewToLevelText": "grew to LV",
"core.asm:GrewToLevelText#2": "!",
"core.asm:GoMonText": "Go!",
"core.asm:DoItMonText": "Do it!",
"core.asm:GoForItMonText": "Go for it!",
"core.asm:YourFoesWeakGetmMonText": "The foe's weak! Get 'em!",
"core.asm:.Text": "!",
"core.asm:EnoughText": "That's enough!",
"core.asm:OKExclamationText": "OK!",
"core.asm:GoodText": "Good job!",
"core.asm:ComeBackText": "Come back!",
"core.asm:Unused_SafariZoneEatingText": "The wild",
"core.asm:Unused_SafariZoneEatingText#2": "is eating!",
"core.asm:Unused_SafariZoneAngryText": "The wild",
"core.asm:Unused_SafariZoneAngryText#2": "is angry!",
# ---- effect_commands.asm (move-effect messages) ---------------------------
"effect_commands.asm:FastAsleepText": "<USER> is fast asleep.",
"effect_commands.asm:WokeUpText": "<USER> woke up!",
"effect_commands.asm:FrozenSolidText": "<USER> is frozen solid!",
"effect_commands.asm:FullyParalyzedText": "<USER> is paralyzed! It can't move!",
"effect_commands.asm:FlinchedText": "<USER> flinched!",
"effect_commands.asm:MustRechargeText": "<USER> must recharge from its attack!",
"effect_commands.asm:DisabledNoMoreText": "<USER> is no longer bound!",
"effect_commands.asm:IsConfusedText": "<USER> is confused!",
"effect_commands.asm:HurtItselfText": "It hurt itself in its confusion!",
"effect_commands.asm:ConfusedNoMoreText": "<USER> snapped out of confusion!",
"effect_commands.asm:AttackContinuesText": "<USER>'s attack continues!",
"effect_commands.asm:CantMoveText": "<USER> can't move!",
"effect_commands.asm:StoringEnergyText": "<USER> is storing energy!",
"effect_commands.asm:UnleashedEnergyText": "<USER> unleashed its stored energy!",
"effect_commands.asm:HungOnText": "<TARGET>",
"effect_commands.asm:HungOnText#2": "hung on with it!",
"effect_commands.asm:EnduredText": "<TARGET> endured the hit!",
"effect_commands.asm:InLoveWithText": "<USER> is in love with <TARGET>!",
"effect_commands.asm:InfatuationText": "<USER> is infatuated and couldn't attack!",
"effect_commands.asm:DisabledMoveText": "<USER>, bound, can't use",
"effect_commands.asm:DisabledMoveText#2": "!",
"effect_commands.asm:LoafingAroundText": "is loafing around.",
"effect_commands.asm:BeganToNapText": "began to nap!",
"effect_commands.asm:WontObeyText": "won't obey!",
"effect_commands.asm:TurnedAwayText": "turned away!",
"effect_commands.asm:IgnoredOrdersText": "ignored orders!",
"effect_commands.asm:NoPPLeftText": "But there was no PP left for the move!",
"effect_commands.asm:AttackMissedText": "But <USER>'s attack missed!",
"effect_commands.asm:CrashedText": "<USER> kept going and crashed into the ground!",
"effect_commands.asm:UnaffectedText": "It doesn't affect <TARGET> at all!",
"effect_commands.asm:DoesntAffectText": "It doesn't seem to affect <TARGET>...",
"effect_commands.asm:CriticalHitText": "A critical hit!",
"effect_commands.asm:OneHitKOText": "It's a one-hit KO!",
"effect_commands.asm:SuperEffectiveText": "It's super effective!",
"effect_commands.asm:NotVeryEffectiveText": "It's not very effective...",
"effect_commands.asm:TookDownWithItText": "<TARGET> took <USER> down with it!",
"effect_commands.asm:RageBuildingText": "<USER>'s RAGE is building!",
"effect_commands.asm:SubTookDamageText": "The SUBSTITUTE took damage for <TARGET>!",
"effect_commands.asm:SubFadedText": "<TARGET>'s SUBSTITUTE faded...",
"effect_commands.asm:FellAsleepText": "<TARGET> fell asleep!",
"effect_commands.asm:AlreadyAsleepText": "<TARGET> is already asleep.",
"effect_commands.asm:WasPoisonedText": "<TARGET> was poisoned!",
"effect_commands.asm:AlreadyPoisonedText": "<TARGET> is already poisoned.",
"effect_commands.asm:BadlyPoisonedText": "<TARGET> was badly poisoned!",
"effect_commands.asm:SuckedHealthText": "Sucked HP from <TARGET>!",
"effect_commands.asm:DreamEatenText": "Ate <TARGET>'s dream!",
"effect_commands.asm:WasBurnedText": "<TARGET> was burned!",
"effect_commands.asm:DefrostedOpponentText": "The flames defrosted <TARGET>!",
"effect_commands.asm:WasFrozenText": "<TARGET> was frozen solid!",
"effect_commands.asm:Text_BattleEffectActivate": "<USER>'s",
"effect_commands.asm:Text_BattleEffectActivate#2": "—",
"effect_commands.asm:Text_BattleEffectActivate#3": "sharply",
"effect_commands.asm:Text_BattleEffectActivate#4": "rose!",
"effect_commands.asm:Text_BattleFoeEffectActivate": "<TARGET>'s",
"effect_commands.asm:Text_BattleFoeEffectActivate#2": "—",
"effect_commands.asm:.BattleStatSharplyFellText": "harshly",
"effect_commands.asm:.BattleStatFellText": "fell!",
"effect_commands.asm:PlayerHitTimesText": "Hit the foe",
"effect_commands.asm:PlayerHitTimesText#2": "time(s)!",
"effect_commands.asm:EnemyHitTimesText": "Hit the foe",
"effect_commands.asm:EnemyHitTimesText#2": "time(s)!",
"effect_commands.asm:BattleMadeWhirlwindText": "'s surroundings began to swirl!",
"effect_commands.asm:BattleTookSunlightText": "absorbed light!",
"effect_commands.asm:BattleLoweredHeadText": "tucked in its head!",
"effect_commands.asm:BattleGlowingText": "is cloaked in a harsh light!",
"effect_commands.asm:BattleFlewText": "flew up high!",
"effect_commands.asm:BattleDugText": "burrowed underground!",
"effect_commands.asm:RecoilText": "<USER> is hit by recoil!",
"effect_commands.asm:BecameConfusedText": "<TARGET> became confused!",
"effect_commands.asm:EliminatedStatsText": "All stat changes were eliminated!",
"effect_commands.asm:WentToSleepText": "<USER> went to sleep!",
"effect_commands.asm:RestedText": "<USER> got healthy and fell asleep!",
"effect_commands.asm:RegainedHealthText": "<USER> regained health!",
"effect_commands.asm:LightScreenEffectText": "<USER> is now stronger against special attacks!",
"effect_commands.asm:ReflectEffectText": "<USER> is now stronger against physical attacks!",
"effect_commands.asm:NoChangesText": "But it had no effect!",
"effect_commands.asm:NothingHappenedText": "But nothing happened.",
"effect_commands.asm:ButItFailedText": "But it failed!",
"effect_commands.asm:DidntAffectText": "But it didn't affect <TARGET>!",
"effect_commands.asm:IsUnaffectedText": "<TARGET> looks unaffected!",
"effect_commands.asm:ParalyzedText": "<TARGET> is paralyzed! Its moves may be blocked!",
"effect_commands.asm:ProtectedByText": "<TARGET> is",
"effect_commands.asm:ProtectedByText#2": "protected by it!",
"effect_commands.asm:.CantEscapeNowText": "<TARGET> can no longer escape!",
"effect_commands.asm:WasDefrostedText": "<USER> was defrosted!",
"effect_commands.asm:SafeguardProtectText": "<TARGET> is protected by the mystical veil!",
"effect_commands.asm:BattleCommand_TimeBasedHealContinue": "<USER> regained health!",
"effect_commands.asm:BattleText_UsersStringBuffer1Activated": "The held",
"effect_commands.asm:BattleText_UsersStringBuffer1Activated#2": "activated!",
# ---- battle menus & misc battle text --------------------------------------
"battle/menu.asm:.MenuData": "FIGHT / ITEM / Pokémon / RUN",
"battle/menu.asm:.MenuData#2": "SAFARI BALL× / THROW BAIT / THROW ROCK / RUN",
"start_battle.asm:BattleText_PlayerPickedUpPayDayMoney": "<PLAYER> picked up",
"start_battle.asm:BattleText_PlayerPickedUpPayDayMoney#2": "yen!",
"start_battle.asm:.YouWin": "You win",
"start_battle.asm:.YouLose": "You lose",
"start_battle.asm:.Draw": "Draw",
"start_battle.asm:WildPokemonAppearedText": "Oh! A wild",
"start_battle.asm:WildPokemonAppearedText#2": "appeared!",
"start_battle.asm:HookedPokemonAttackedText": "The hooked",
"start_battle.asm:HookedPokemonAttackedText#2": "attacked!",
"start_battle.asm:WantsToBattleText": "'s",
"start_battle.asm:WantsToBattleText#2": "wants to battle!",
"used_move_text.asm:UsedMove1Text": "'s",
"used_move_text.asm:UsedMove2Text": "—",
"used_move_text.asm:.UsedInsteadText": "ignored orders and",
"used_move_text.asm:EndUsedMove1Text": "used it!",
"used_move_text.asm:EndUsedMove2Text": "did it!",
"used_move_text.asm:EndUsedMove3Text": "did it!",
"used_move_text.asm:EndUsedMove4Text": "attack!",
"used_move_text.asm:EndUsedMove5Text": "!",
"items.asm:.EnemyWithdrewText": "The foe",
"items.asm:.EnemyWithdrewText#2": "withdrew it!",
"items.asm:PrintText_UsedItemOn": "used —",
"items.asm:PrintText_UsedItemOn#2": "on",
"items.asm:PrintText_UsedItemOn#3": "the item!",
# ---- battle/move_effects (per-effect messages) ----------------------------
"attract.asm:.FellInLoveText": "<TARGET> fell in love!",
"baton_pass.asm:BattleText_MonIsAlreadyOut_0d": "is already out.",
"bell_chime.asm:BellChimedText": "<USER>'s status returned to normal!",
"conversion.asm:.got_mon_types": "Copied <TARGET>'s type onto itself!",
"conversion2.asm:BattleCommand_Conversion2": "Changed <TARGET>'s type",
"conversion2.asm:BattleCommand_Conversion2#2": "!",
"destiny_bond.asm:DestinyBondEffectText": "<USER> is trying to take its foe down with it!",
"disable.asm:MoveDisabledText": "<TARGET>'s",
"disable.asm:MoveDisabledText#2": "was DISABLED!",
"encore.asm:GotAnEncoreText": "<TARGET> got an ENCORE!",
"endure.asm:BracedItselfText": "<USER> braced itself!",
"focus_energy.asm:GettingPumpedText": "<USER> is getting pumped!",
"foresight.asm:.IdentifiedText": "<USER> identified <TARGET>!",
"gen1_heal.asm:Unused_WentToSleepText": "<USER> went to sleep!",
"gen1_heal.asm:Unused_RestedText": "<USER> got healthy and fell asleep!",
"gen1_heal.asm:Unused_RegainedHealthText": "<USER> regained health!",
"leech_seed.asm:WasSeededText": "Planted a seed on <TARGET>!",
"leech_seed.asm:EvadedText": "<TARGET> evaded the attack!",
"lock_on.asm:TookAimText": "Took aim at <TARGET>!",
"magnitude.asm:MagnitudeText": "MAGNITUDE",
"magnitude.asm:MagnitudeText#2": "!!",
"mimic.asm:MimicLearnedMoveText": "<USER> learned",
"mimic.asm:MimicLearnedMoveText#2": "!",
"mirror_move.asm:MirrorMoveFailedText": "But the MIRROR MOVE failed!",
"mist.asm:MistText": "<USER> became shrouded in white mist!",
"nail_down.asm:BattleCommand_NailDown": "<USER> drove a nail into itself! <TARGET> was cursed!",
"nightmare.asm:.StartedNightmareText": "<TARGET> began having a nightmare!",
"pain_split.asm:SharedPainText": "The two shared their HP evenly!",
"pay_day.asm:CoinsScatteredText": "Coins scattered everywhere!",
"perish_song.asm:StartPerishText": "Both Pokémon will faint in 3 turns!",
"protect.asm:ProtectedItselfText": "<USER> protected itself!",
"rain_dance.asm:BattleCommand_StartRain": "It started to rain hard!",
"rapid_spin.asm:ReleasedByText": "<USER> was freed from <TARGET>'s hold!",
"safeguard.asm:.CoveredByVeilText": "<USER> became cloaked in a mystical veil!",
"sandstorm.asm:.SandstormBrewedText": "<TARGET> was caught in the sandstorm!",
"sketch.asm:SketchedText": "<USER>",
"sketch.asm:SketchedText#2": "was copied down!",
"spikes.asm:BattleCommand_Spikes": "SPIKES scattered around <TARGET>'s feet!",
"spite.asm:SpiteEffectText": "<TARGET>'s",
"spite.asm:SpiteEffectText#2": "—",
"spite.asm:SpiteEffectText#3": "was cut!",
"substitute.asm:MadeSubstituteText": "<USER>'s SUBSTITUTE appeared!",
"substitute.asm:HasSubstituteText": "But <USER> already has a SUBSTITUTE!",
"substitute.asm:TooWeakSubText": "But <USER> didn't have enough HP to make a SUBSTITUTE!",
"sunny_day.asm:BattleCommand_StartSun": "The sunlight got bright!",
"move_effects/teleport.asm:FledFromBattleText": "<USER> fled from battle!",
"move_effects/teleport.asm:FledInFearText": "<TARGET> got scared and fled!",
"move_effects/teleport.asm:BlownAwayText": "<TARGET> was blown away!",
"thief.asm:StoleText": "<USER> stole",
"thief.asm:StoleText#2": "from <TARGET>!",
"transform.asm:TransformedText": "<USER>",
"transform.asm:TransformedText#2": "transformed into it!",
# ---- battle/ai ------------------------------------------------------------
"trainer_gear.asm:.OutOfRangeText": "Out of range",
"trainer_gear.asm:.DarnText": "Darn......",
"trainer_gear.asm:TrainerGear_RadioText": "Press A to tune in!",
# ---- events / intro (oak_speech, title) -----------------------------------
"oak_speech.asm:OakSpeechDemo": "Welcome to the world of Pokémon! As you know, I'm Prof. Oak! I've asked you here for one reason: I'd like your help making a new Pokédex! Of course, your partner Pokémon and a backpack are ready for you. The backpack holds a POTION and a POKé BALL, so you're all set! Your rival has already set off. Do your best not to lose to them!",
"oak_speech.asm:OakSpeech1": "Hello there! Welcome to the world of Pokémon! My name is Oak. People affectionately call me the Pokémon Professor.",
"oak_speech.asm:OakSpeech2": "As you surely know, creatures called Pokémon live all over this world!",
"oak_speech.asm:OakSpeech3": "People keep Pokémon as pets, use them in battles, and... studying Pokémon is what I do.",
"oak_speech.asm:OakSpeech4": "First, tell me your name!",
"oak_speech.asm:OakSpeech5": "And this boy is your childhood friend and rival... Er? What was his name again?",
"oak_speech.asm:OakSpeech6": "Now, let's record the memorable day you set out! Set the time as accurately as you can, too!",
"oak_speech.asm:OakSpeech7": "<PLAYER>! From here on, your story begins! To a world of dreams and adventures with Pokémon! Let's go!",
"oak_speech.asm:ChoosePlayerNameEndText": "Hmm... So it's <PLAYER>!",
"oak_speech.asm:ChooseRivalNameEndText": "I see, that's right — the name was <RIVAL>.",
"title.asm:SRAMClear_Message": "Clear all save-data areas?",
"title.asm:SRAMClear_TextChoice": "NO / YES",
# ---- events / trade animation ---------------------------------------------
"trade_animation.asm:.OTMonData": "──·. OT/ '·.",
"trade_animation.asm:.MonWasSentToText": "was safely",
"trade_animation.asm:.MonWasSentToText#2": "taken in.",
"trade_animation.asm:.BidsFarewellToMonText": "reluctantly bids farewell as it",
"trade_animation.asm:.MonNameBidsFarewellText": "is sent off.",
"trade_animation.asm:.TakeGoodCareOfMonText": "Please take good care of it.",
"trade_animation.asm:.ForYourMonSendsText": "in exchange for",
"trade_animation.asm:.ForYourMonSendsText#2": "sends over",
"trade_animation.asm:.OTSendsText": "gives you",
"trade_animation.asm:.OTSendsText#2": ".",
"trade_animation.asm:.WillTradeText": "Now trading",
"trade_animation.asm:.WillTradeText#2": "'s",
"trade_animation.asm:.WillTradeText#3": "for",
"trade_animation.asm:.ForYourMonWillTradeText": "'s",
"trade_animation.asm:.ForYourMonWillTradeText#2": "will be traded!",
# ---- events / fishing (old anims) -----------------------------------------
"player_animations_old.asm:NoNibbleText": "Not even a nibble......",
"player_animations_old.asm:NothingHereText": "Looks like there's nothing here......",
"player_animations_old.asm:ItsABiteText": "Oh! A bite, a bite!",
# ---- pokemon/ (party, storage, evolve, moves) -----------------------------
"add_mon.asm:RecievePokemonText": "<PLAYER> got",
"add_mon.asm:RecievePokemonText#2": "!",
"add_mon.asm:BoxCantHoldText": "Can't carry any more Pokémon, so it was sent to BOX",
"add_mon.asm:BoxCantHoldText#2": "in",
"add_mon.asm:BoxCantHoldText#3": "on the <PC>!",
"add_mon.asm:BoxFullText": "You can't carry any more Pokémon! The BOX is full too, so none can be sent! Please swap the BOX at a Pokémon Center.",
"bills_pc.asm:.PCWhatText": "What are you going to do?",
"bills_pc.asm:.MenuData": "Look at Pokémon / Withdraw Pokémon / Deposit Pokémon / Release Pokémon / Change BOX / Goodbye",
"bills_pc.asm:.PCGottaHavePokemonText": "No dice if you've got no Pokémon!",
"bills_pc.asm:.PCNoSingleMonText": "You don't even have one!",
"bills_pc.asm:.PCCantDepositLastMonText": "You can't deposit your last Pokémon!",
"bills_pc.asm:.PCCantTakeText": "You can't take any more Pokémon.",
"bills_pc.asm:.OnceReleasedText": "Are you sure you want to release it?",
"bills_pc.asm:.DummyBoxText": "Dummy Box",
"bills_pc.asm:.Pokemon": "Pokémon in my care",
"bills_pc.asm:.BoxChangeUnderDevText": "BOX change is under development!",
"bills_pc.asm:.ChangeBoxSaveText": "When you change a BOX, the game is saved at the same time. ...Is that okay?",
"bills_pc.asm:.MenuData#2": "Change Box / Change Name / Stop",
"bills_pc.asm:.CurrentBox": "Box / Current Box",
"bills_pc.asm:.SpeciesNameLevel": "Species  Name   Level",
"bills_pc.asm:.PCString_ChooseaPKMN": "Which Pokémon would you like to see?",
"bills_pc.asm:.PokemonSelected": "Pokémon selected!",
"evolve.asm:CongratulationsYourPokemonText": "Congratulations!",
"evolve.asm:CongratulationsYourPokemonText#2": "—",
"evolve.asm:EvolvedIntoText": "evolved into",
"evolve.asm:StoppedEvolvingText": "Huh...?",
"evolve.asm:StoppedEvolvingText#2": "stopped evolving!",
"evolve.asm:EvolvingText": "... Oh!?",
"evolve.asm:EvolvingText#2": "is acting strangely...!",
"knows_move.asm:AlreadyKnowsMoveText": "already knows",
"knows_move.asm:AlreadyKnowsMoveText#2": ".",
"learn.asm:LearnedMoveText": "learned",
"learn.asm:LearnedMoveText#2": "!",
"learn.asm:MoveAskForgetText": "Which move should be forgotten?",
"learn.asm:StopLearningMoveText": "Well then...",
"learn.asm:StopLearningMoveText#2": "give up on learning it?",
"learn.asm:DidNotLearnMoveText": "did not learn",
"learn.asm:DidNotLearnMoveText#2": ".",
"learn.asm:AskForgetMoveText": "wants to learn a new move,",
"learn.asm:AskForgetMoveText#2": "! But",
"learn.asm:AskForgetMoveText#3": "already knows 4 moves — the most it can!",
"learn.asm:AskForgetMoveText#4": "Forget another move to make room?",
"learn.asm:Text_1_2_and_Poof": "1, 2 and...",
"learn.asm:MoveForgotText": "Poof!",
"learn.asm:MoveForgotText#2": "—",
"learn.asm:MoveForgotText#3": "completely forgot how to use it! And...!",
"learn.asm:MoveCantForgetHMText": "That's an important move. It can't be forgotten!",
"mon_stats.asm:.StatNames": "ATTACK / DEFENSE / SPCL.ATK / SPCL.DEF / SPEED",
"mon_submenu.asm:.MenuText": "SWITCH / STATS / CANCEL",
"move_mon.asm:WasSentToBillsPCText": "was sent to Masaki's PC!",
"move_mon.asm:WasSentToSomeonesPCText": "was transferred to someone's PC!",
"move_mon.asm:NewDexDataText": "New Pokédex data was recorded!",
"move_mon.asm:GotItText": "Got it!",
"move_mon.asm:AskGiveNicknameText": "Would you like to give it a name?",
"nickname_unused.asm:AskGiveNickname_Old": "Give it a nickname?",
"party_menu.asm:.string_able": "ABLE",
"party_menu.asm:.string_not_able": "NOT ABLE",
"party_menu.asm:.PlacePartyMonEvoStoneCompatibility": "ABLE",
"party_menu.asm:.PlacePartyMonEvoStoneCompatibility#2": "NOT ABLE",
"party_menu.asm:.PlacePartyMonEvoStoneCompatibility#3": "♂",
"party_menu.asm:.PlacePartyMonEvoStoneCompatibility#4": "♀",
"party_menu.asm:ChooseAMonString": "Please choose a Pokémon.",
"party_menu.asm:UseOnWhichPKMNString": "Use it on which Pokémon?",
"party_menu.asm:WhichPKMNString": "Which Pokémon will you send out?",
"party_menu.asm:TeachWhichPKMNString": "Teach it to which Pokémon?",
"party_menu.asm:MoveToWhereString": "Move it to where?",
"party_menu.asm:ChooseFirstMonString": "Please choose the first Pokémon.",
"party_menu.asm:ChooseSecondMonString": "Please choose the second Pokémon.",
"party_menu.asm:RecoveredSomeHPText": "'s HP",
"party_menu.asm:RecoveredSomeHPText#2": "was restored.",
"party_menu.asm:CuredOfPoisonText": "was cured of its poison, clean and clear!",
"party_menu.asm:RidOfParalysisText": "was rid of its paralysis.",
"party_menu.asm:BurnWasHealedText": "'s burn was healed.",
"party_menu.asm:_WasDefrostedText": "was thawed out.",
"party_menu.asm:_WokeUpText": "woke up.",
"party_menu.asm:HealthReturnedText": "became healthy!",
"party_menu.asm:RevitalizedText": "regained its energy!",
"party_menu.asm:_GrewToLevelText": "'s level",
"party_menu.asm:_GrewToLevelText#2": "went up.",
"stats_screen.asm:StatusText_StatusType": "STATUS / TYPE",
"stats_screen.asm:StatusText_OK": "OK",
"stats_screen.asm:StatusText_ExpPoints": "EXP. Points",
"stats_screen.asm:StatusText_Ato": "TO NEXT",
"stats_screen.asm:StatusText_De": "LV",
"stats_screen.asm:LoadGreenPage": "ITEM",
"stats_screen.asm:LoadGreenPage#2": "NONE",
"stats_screen.asm:LoadGreenPage#3": "MOVES",
"stats_screen.asm:LoadBluePage": "<ID> No./ OT/",
"stats_screen.asm:LoadBluePage#2": "STATS",
"display_dex_entry.asm:PokedexText_HeightWeight": "HT  ??? / WT  ???",
# ---- pokedex --------------------------------------------------------------
"pokedex.asm:String_SEEN": "SEEN",
"pokedex.asm:String_OWN": "OWN",
"pokedex.asm:String_SELECT_SEARCH": "SELECT ▶ SEARCH",
"pokedex.asm:String_START_VARIANTS": "START ▶ VARIANTS",
"pokedex.asm:.NameNotSeen": "-----",
"pokedex_2.asm:.SearchByTypeString": "Search by type",
"pokedex_2.asm:.SelectedString": "Selected",
"pokedex_2.asm:FirstTypeSelectedMenu": "Search / Add another / Stop",
"pokedex_2.asm:SecondTypeSelectedMenu": "Search / Redo / Stop",
"pokedex_2.asm:Pokedex_PlaceSearchScreenTypeStrings": "----",
"pokedex_2.asm:.UnownVariantsString": "UNOWN variants",
"pokedex_2.asm:.VariantsDiscoveredString": "variants found!",
"pokedex_2.asm:.UnownString": "UNOWN",
# ---- link -----------------------------------------------------------------
"link.asm:String_PleaseWait": "Preparing to link!",
"link.asm:.String_Stats_Trade": "View Stats   Offer Trade",
"link.asm:LinkAbnormalMonText": "The",
"link.asm:LinkAbnormalMonText#2": "your partner chose seems to have corrupted data!!",
"link.asm:.CancelString": "Cancel Trade",
"link.asm:String_TradeCancel": "Trade / Cancel",
"link.asm:LinkAskTradeForText": "and",
"link.asm:LinkAskTradeForText#2": "will be traded.",
"link.asm:String_TradeCompleted": "Trade complete!",
"link.asm:String_TooBadTheTradeWasCanceled": "Too bad — the trade was canceled.",
"link_2.asm:.ComeOnInText": "Come on in.",
"link_2.asm:.mon_too_new_Text": "can't be taken along!",
"link_2.asm:.move_too_new_Text": "knows",
"link_2.asm:.mon_too_new_Text2": "and can't be taken along!",
"link_2.asm:Text_LinkInstructions": "This is a special guide for those who have connected a link cable with a friend!",
"link_2.asm:CableClubWelcomeText": "Welcome to the Cable Club! Bzzt.",
"link_2.asm:CableClubCheckInText": "The reception is over here. Before we start the link, I'll save the game. Bzzt.",
"link_2.asm:CableClubWaitText": "Please wait a moment. Bzzt.",
"link_2.asm:CableClubLinkFailureText": "You've waited a long time, so we're canceling reception! Please contact your friend and come again!",
"link_2.asm:CableClubExitText": "Please come again.",
"link_2.asm:CableClubConnectingText": "We are getting ready right now.",
"link_2.asm:Text_Receptionist_PleaseComeInDuplicate": "Now then, I'll show you in.",
"link_2.asm:Text_Receptionist_CommunicationCancelled": "The link was canceled.",
"link_2.asm:Text_Receptionist_TemporaryStagingInLinkRoom": "For now, we'll treat you as having entered the link room.",
"link_2.asm:Text_Receptionist_CantLinkToThePast": "You can't link with #1 here.",
"link_2.asm:Text_Receptionist_IncompatibleRooms": "You and your friend seem to have picked different rooms.",
"link_2.asm:Text_Receptionist_PleaseComeIn": "Please head into the room.",
"link_2.asm:Text_Receptionist_Options": "Trade Center / Colosseum / Stop",
"link_2.asm:Text_Receptionist_Old_Wait": "Just a moment, please.",
"place_waiting_text.asm:PlaceWaitingText": "Waiting to link!",
# ---- events / save & menus ------------------------------------------------
"empty_sram.asm:WouldYouLikeToSaveTheGameText": "Record your progress so far in the Pokémon Report?",
"empty_sram.asm:SavedTheGameText": "<PLAYER> firmly recorded it in the Report!",
"empty_sram.asm:AlreadyASaveFileText": "The previously written Report will be lost. Is it okay to overwrite it?",
"empty_sram.asm:AnotherSaveFileText": "The previously written Report is different from this one. Is it okay to overwrite it?",
"empty_sram.asm:.MenuData": "Hero <PLAYER> / Badges owned    / Pokédex    caught / Play time",
"empty_sram.asm:.MenuData#2": "TEST",
"empty_sram.asm:.SaveFileCorruptedText": "The Report's contents are corrupted!!",
"frame_type_dialog.asm:.MenuData": "1st / 2nd / 3rd / 4th / 5th / 6th / 7th / 8th",
"main_menu.asm:.Strings": "Continue / New Game / Options / Play with Pokémon / Set Clock",
"main_menu.asm:PlayerInfoText": "Hero / Badges owned    / Pokédex    caught / Play time",
"menu/menu.asm:.WindowSaveAreaOverflowText": "The window save area overflowed.",
"menu/menu.asm:.WindowPoppingErrorText": "There's no window that can be popped!",
"menu_2.asm:.CancelString": "--CANCEL--",
"options_menu.asm:.OptionsText_TextSpeed": "Text Speed / FAST  MID  SLOW",
"options_menu.asm:.OptionsText_BattleScene": "Battle Animation / DETAILED  SKIP",
"options_menu.asm:.OptionsText_BattleStyle": "Battle Rule / SWITCH  SET",
"options_menu.asm:.OptionsText_Sound": "MONO     STEREO",
"options_menu.asm:.OptionsText_Cancel": "DONE",
"options_menu.asm:.OptionsText_FrameType": "Change Frame",
"reset_dialog.asm:_ResetConfirmText": "Really reset?",
"scrolling_menu.asm:.CancelString": "Stop",
"set_clock_dialog.asm:.DayString": "day",
"set_clock_dialog.asm:.HoursString": "hr.",
"set_clock_dialog.asm:.MinutesString": "min.",
"set_clock_dialog.asm:SetClockDialog_WhatDayIsIt": "Now, what day of the week is it?",
"set_clock_dialog.asm:SetClockDialog_HowManyHours": "What hour is it now?",
"set_clock_dialog.asm:SetClockDialog_HowManyMinutes": "And how many minutes past?",
"set_clock_dialog.asm:SetClockDialog_ConfirmTimeDate": "Day  hr.  min. Is this really correct?",
"set_time.asm:AdjustTimeText": "hr.",
"set_time.asm:AdjustTimeText#2": "min.?",
"set_time.asm:AdjustTimeEndText": "hr.",
"set_time.asm:AdjustTimeEndText#2": "min.?",
"start_menu.asm:.Strings": "Pokédex / Pokémon / Backpack / <PLAYER> / Report / Options / Close / Frame Line / Reset",
"start_menu.asm:DebugBackpackLoop": "Ordinary Items",
"start_menu.asm:KeyItemsPocketText": "Key Items",
"start_menu.asm:BackpackHeaderText": "Inside the Backpack",
"start_menu.asm:DebugSelectedItemMenu": "USE / TOSS / REGISTER",
"start_menu.asm:SelectedItemMenu": "USE / TOSS",
"start_menu.asm:.TossedText": "— how many should be tossed?",
"start_menu.asm:.TossVerifyText": "Toss",
"start_menu.asm:.TossVerifyText#2": "— is that okay?",
"start_menu.asm:.TossedTextCopy": "was tossed!",
"start_menu.asm:.CantDropItemText": "That's a very important item. It can't be tossed!",
"start_menu.asm:.CantUseHMText": "Under development. It can't be used yet.",
"start_menu.asm:.CantUseHereText": "Prof. Oak's words... <PLAYER>! There's a time and place to use this!",
"start_menu.asm:.NoItemsText": "You don't have a single item!",
"start_menu.asm:.BallHolderText": "Ball Holder",
"start_menu.asm:.RegisteredItemText": "was registered to the SELECT button!",
"start_menu.asm:.CantRegisterToolText": "That item can't be registered!",
"start_menu.asm:.Items": "Give item / Take item",
"start_menu.asm:ItemCantHeldText": "can't be held.",
"start_menu.asm:PokemonSwapItemText": "was holding",
"start_menu.asm:PokemonSwapItemText#2": ", took it off, and",
"start_menu.asm:PokemonSwapItemText#3": "was given instead!",
"start_menu.asm:PokemonHoldItemText": "was given",
"start_menu.asm:PokemonHoldItemText#2": "to hold!",
"start_menu.asm:PokemonNotHoldingText": "isn't holding anything!",
"start_menu.asm:ItemStorageFullText": "The Bag is full, so the item can't be taken off!",
"start_menu.asm:PokemonTookItemText": "took",
"start_menu.asm:PokemonTookItemText#2": "off!",
"start_menu.asm:PokemonAskSwapItemText": "is",
"start_menu.asm:PokemonAskSwapItemText#2": "already holding an item. Swap the held item?",
"start_menu.asm:PartyMailMenu": "Read Mail / Take Mail / Stop",
"start_menu.asm:PartyMailMenu#2": "Taking off Mail erases its message. Is that okay?",
"start_menu.asm:PartyMailMenu#3": "from",
"start_menu.asm:PartyMailMenu#4": "the Mail was taken off!",
"start_menu.asm:PartyMailMenu#5": "The Bag is full, so the Mail can't be taken off!",
"start_menu.asm:NotHealthyEnoughText": "Its HP is too low!",
"start_menu.asm:NeedNewBadgeText": "It can't be used until you get a new Badge!",
"start_menu.asm:PartyTypeText": "TYPE/     POWER/",
"start_menu.asm:PartyPokeDivider": "---",
"start_menu.asm:PartyMoveText": "Move it to where?",
"start_menu.asm:.NothingRegisteredText": "You pressed the SELECT button! ...but nothing happened!",
"start_menu.asm:TrainerCardText": "NAME/ / Money / Pokédex",
"start_menu.asm:TrainerCardDexEntriesText": "caught",
"start_menu.asm:TrainerCardLeagueBadgesTextTiles": "Pokémon League Badges",
"text_entry.asm:.Pokemon": "'s nickname?",
"text_entry.asm:.NameText": "Your name?",
"text_entry.asm:.RivalText": "Your rival's name?",
"text_entry.asm:.MomText": "Your mother's name?",
"text_entry.asm:.BoxText": "The BOX's name?",
"text_entry.asm:Dakutens": "(voiced-kana chart: ka-ga, sa-za, ta-da, ha-ba rows, hiragana and katakana)",
"text_entry.asm:Handakutens": "(half-voiced-kana chart: ha-pa row, hiragana and katakana)",
"text_entry.asm:MailPromptText": "Write your Mail.",
"text_entry.asm:MailLoadedText": "MAIL!!!",
"text_entry.asm:MailTextExtra": "?!12345 67890- yen",
# ---- items/ ---------------------------------------------------------------
"check_tossable_item.asm:.ItemsDiscardedText": "was thrown away!",
"check_tossable_item.asm:.ItemsThrowAwayText": "Are you sure you want to throw it away?",
"check_tossable_item.asm:.ItemsTooImportantText": "That's a very important item. You can't throw it away!",
"item_effects.asm:Unreferenced_BallDodgedText": "It dodged the thrown BALL! This Pokémon can't be caught!",
"item_effects.asm:Unreferenced_BallMissedText": "You missed the Pokémon!",
"item_effects.asm:BallBrokeFreeText": "Oh no! The Pokémon broke free!",
"item_effects.asm:BallAppearedCaughtText": "Aww! It appeared to be caught!",
"item_effects.asm:BallAlmostHadItText": "Aargh! Almost had it!",
"item_effects.asm:BallSoCloseText": "Shoot! It was so close, too!",
"item_effects.asm:Text_GotchaMonWasCaught": "Gotcha!",
"item_effects.asm:Text_GotchaMonWasCaught#2": "was caught!",
"item_effects.asm:BallSentToBillsPCText": "was transferred to Masaki's PC!",
"item_effects.asm:BallSentToSomeonesPCText": "was transferred to someone's PC!",
"item_effects.asm:NewDexDataText_CaughtMon": "New Pokédex data was recorded!",
"item_effects.asm:AskGiveNicknameText_CaughtMon": "The caught",
"item_effects.asm:AskGiveNicknameText_CaughtMon#2": "— give it a name?",
"item_effects.asm:ItemStatRoseText": "'s",
"item_effects.asm:ItemStatRoseText#2": "base points rose!",
"item_effects.asm:ItemWontHaveEffectText": "It won't have any effect.",
"item_effects.asm:.ItemCantUseOnMonText": "It can't be used on that Pokémon.",
"item_effects.asm:.PlayedFluteText": "Played the POKé FLUTE! Mmm! What a wonderful tone!",
"item_effects.asm:.FluteWakeUpText": "All Pokémon woke up!",
"item_effects.asm:.PlayedTheFlute": "<PLAYER> played the POKé FLUTE!",
"item_effects.asm:CoinCaseCountText": "Your coins:",
"item_effects.asm:CoinCaseCountText#2": "coins",
"item_effects.asm:RaiseThePPOfWhichMoveText": "Raise the PP of which move?",
"item_effects.asm:RestoreThePPOfWhichMoveText": "Restore the PP of which move?",
"item_effects.asm:PPIsMaxedOutText": "'s PP can't be raised any further.",
"item_effects.asm:PPsIncreasedText": "'s PP increased!",
"item_effects.asm:PPRestoredText": "PP was restored!",
"item_effects.asm:.BootedTMText": "Booted up the <TM>!",
"item_effects.asm:.BootedHMText": "Booted up the HM!",
"item_effects.asm:.ContainedMoveText": "Inside was",
"item_effects.asm:.ContainedMoveText#2": ", recorded on it!",
"item_effects.asm:.ContainedMoveText#3": "Teach it to a Pokémon?",
"item_effects.asm:.TMHMNotCompatibleText": "and",
"item_effects.asm:.TMHMNotCompatibleText#2": "aren't compatible!",
"item_effects.asm:.TMHMNotCompatibleText#3": "can't learn it!",
"item_effects.asm:ItemOakWarningText": "Prof. Oak's words... <PLAYER>! There's a time and place to use this!",
"item_effects.asm:ItemBelongsToSomeoneElseText": "It's an important item you're holding for someone! You can't use it!",
"item_effects.asm:ItemWontHaveAnyEffectText": "It won't have any effect.",
"item_effects.asm:BallBlockedText": "<TRAINER> knocked the BALL away!",
"item_effects.asm:BallDontBeAThiefText": "Taking someone else's things makes you a thief!",
"item_effects.asm:NoCyclingText": "You can't ride the BICYCLE here.",
"item_effects.asm:ItemCantGetOnText": "You can't ride",
"item_effects.asm:ItemCantGetOnText#2": "here.",
"item_effects.asm:BallBoxFullText": "The BOX of deposited Pokémon is full, so it can't be used!",
"item_effects.asm:ItemUsedText": "<PLAYER> used",
"item_effects.asm:ItemUsedText#2": "!",
"item_effects.asm:ItemGotOnText": "<PLAYER> got on",
"item_effects.asm:ItemGotOnText#2": ".",
"item_effects.asm:ItemGotOffText": "<PLAYER> got off",
"item_effects.asm:ItemGotOffText#2": ".",
"tm_holder.asm:BootedTMText": "Booted up the <TM>!",
"tm_holder.asm:Unreferenced_BootedHMText": "Booted up the HM!",
"tm_holder.asm:ContainedMoveText": "Inside was",
"tm_holder.asm:ContainedMoveText#2": ", recorded on it!",
"tm_holder.asm:ContainedMoveText#3": "Teach it to a Pokémon?",
"tm_holder.asm:TMHMNotCompatibleText": "and",
"tm_holder.asm:TMHMNotCompatibleText#2": "aren't compatible!",
"tm_holder.asm:TMHMNotCompatibleText#3": "can't learn it!",
"tm_holder.asm:TMHM_PowerString": "POWER/",
"tm_holder.asm:TMHM_ThreeDashesString": "---",
"tm_holder.asm:TMHM_TypeString": "TYPE/",
"tm_holder.asm:.NoRoomTMHMText": "can't be held any more!",
"tm_holder.asm:.ReceivedTMHMText": "was obtained!",
# ---- pokemon/ breeder -----------------------------------------------------
"breeder.asm:.IntroText": "I'm a Breeder. So, what will you do?",
"breeder.asm:.MenuData": "Deposit / Withdraw / Stop",
"breeder.asm:.DepositedText": "Deposited!",
"breeder.asm:.AlreadyHasTwoPokemonText": "I'm already looking after two Pokémon.",
"breeder.asm:.CheckOnPokemonText": "Stop the breeding?",
"breeder.asm:.DoesntHavePokemonText": "I'm not looking after a single Pokémon, though.",
"breeder.asm:.WithdrawnText": "Withdrawn!",
"breeder.asm:.BoxAndPartyFullText": "Both your party and Masaki's PC seem full of Pokémon.",
"breeder.asm:.LetsMakeBabiesText": "Now then, let's breed them!",
"breeder.asm:.SeemToGetAlongText": "They seem to get along well.",
"breeder.asm:.DontSeemToGetAlongText": "They don't seem to get along.",
"breeder.asm:.GendersDontMatchText": "Their genders don't match.",
"breeder.asm:.NoEggYetText": "Sorry, but it seems nothing has hatched yet.",
"breeder.asm:.EggLaidText": "An Egg was laid! Will you take it?",
# ---- overworld / field moves ----------------------------------------------
"field_moves.asm:Text_CantUseCutHere": "It can't be used here.",
"field_moves.asm:Text_CutItDown": "used CUT!",
"field_moves.asm:Text_CantSurfHere": "You can't ride here.",
"field_moves.asm:Text_UsedSurf": "—",
"field_moves.asm:Text_UsedSurf#2": "let you ride it!",
"field_moves.asm:Text_CantUseFlyHere": "It can't be used here!",
"field_moves.asm:Text_CantUseDigHere": "It can't be used here!",
"field_moves.asm:Text_CantFindDestination": "The destination can't be found.",
"field_moves.asm:Text_CantUseTeleportHere": "It can't be used here!",
"field_moves.asm:Text_ReturnToLastMonCenter": "You'll return to the last Pokémon Center you stopped at.",
# ---- pokecenter_pc --------------------------------------------------------
"pokecenter_pc.asm:.NotConnectedText": "... it seems the ... wasn't connected ...",
"pokecenter_pc.asm:.TurnOnText": "Booted up the computer! Connected to the network!",
"pokecenter_pc.asm:.MenuStrings": "<PLAYER>'s PC / ???'s PC / Oak's PC / Hall of Fame / Log off",
"pokecenter_pc.asm:.NoPokemonText": "Beep! People without Pokémon can't use this!",
"pokecenter_pc.asm:.SkarmoryText": "Pokémon Journal Home Page ... ... ... ... ... ... New Pokémon discovered!! Name: YOROIDORI. Its trademark is wings as hard as steel. It has been decided it will be classified not only as a Flying type but also as a new METAL type. Further research is awaited. ... ... ... ... ... ...",
"pokecenter_pc.asm:.TooManyConnectionsText": "The line is congested and you can't connect.",
"pokecenter_pc.asm:.ClosedPCText": "You stopped connecting to the network.",
"pokecenter_pc.asm:.MenuStrings#2": "Withdraw / Deposit / Toss / Log off",
"pokecenter_pc.asm:.TurnOnText#2": "<PLAYER> connected to their PC and called up the item-storage system!",
"pokecenter_pc.asm:.ShutDownText": "<PLAYER> disconnected from their PC.",
"pokecenter_pc.asm:.HowManyToWithdrawText": "How many should be withdrawn?",
"pokecenter_pc.asm:.WithdrewItemsText": "Withdrew",
"pokecenter_pc.asm:.WithdrewItemsText#2": "of them.",
"pokecenter_pc.asm:.NoRoomWithdrawText": "Your Bag is full, so they can't be withdrawn!",
"pokecenter_pc.asm:.NoItemsText": "You don't have a single item!",
"pokecenter_pc.asm:.CantDepositText": "TMs can't be deposited!",
"pokecenter_pc.asm:.CantDepositBallText": "The Ball Holder can't be deposited!",
"pokecenter_pc.asm:.HowManyDepositText": "How many should be deposited?",
"pokecenter_pc.asm:.DepositItemsText": "Deposited",
"pokecenter_pc.asm:.DepositItemsText#2": "of them.",
"pokecenter_pc.asm:.NoRoomDepositText": "Storage is full. No more can be deposited!",
# ---- events / std scripts (signs, TV, radio) ------------------------------
"events/std_scripts.asm:_Unreferenced_PokemonNewsScript": "<PLAYER> switched on the radio! 'J-O-P-M — this is the Pokémon Broadcasting Station. Here is the Pokémon News. ...The world-renowned Pokémon researcher Prof. Oak has vanished from Kanto. Some believe he moved on in search of a new place to research, but there's also a chance he's been caught up in some incident, and those close to him are very worried. ...That's all. This has been the Pokémon News. ............'",
"events/std_scripts.asm:.PokemonBooksText": "The Pokémon picture books are all here!",
"events/std_scripts.asm:.FridgeText": "Inside it's... almost empty...",
"events/std_scripts.asm:.StoveText": "The gas stove's flame is out. Safety first!",
"events/std_scripts.asm:.SinkText": "A sparkling-clean sink! What's for dinner tonight?",
"events/std_scripts.asm:.PokecenterSignText": "Restore your Pokémon's health! Pokémon Center",
"events/std_scripts.asm:.WindowText": "The window is dirty, isn't it?",
"events/std_scripts.asm:.TVDayText": "Pikachu is battling a Spearow... Satoshi is teary-eyed... It's the Pokémon cartoon!",
"events/std_scripts.asm:.TVNightText": "A Primeape is rampaging... Satoshi is running for his life!... It's the Pokémon cartoon!",
"events/std_scripts.asm:.TVMorningText": "Bulbasaur is sulking... Satoshi is troubled... It's the Pokémon cartoon!",
"town_map.asm:ChooseADestinationText": "Please choose a destination.",
"town_map.asm:.String_SNest": "'s nest",
# ---- games/ (minigames) ---------------------------------------------------
"memory_minigame.asm:.YeahText": "Got it!",
"memory_minigame.asm:.DarnText": "Too bad...",
"memory_minigame.asm:MemoryGame_InitStrings": "Taken",
"memory_minigame.asm:MemoryGame_InitStrings#2": "turns left",
"pikachu_minigame.asm:.DisplayText": "START button ▶ Title screen",
"poker_minigame.asm:.ExchangeText": "Swap",
"poker_minigame.asm:.StayAsIsText": "Keep",
"poker_minigame.asm:PokerMinigame_InstructionsText": "Pick cards with A, play your hand with B!",
"poker_minigame.asm:PokerMinigame_NoCoinsText": "You've run out of coins...",
"poker_minigame.asm:PokerMinigame_ReplayText": "Play one more round?",
"poker_minigame.asm:PokerMinigame_DoubleUpText": "Take on the Double Up?",
"poker_minigame.asm:PokerMinigame_DoubleUpInstructionsText": "Is the right card higher or lower than the left?",
"poker_minigame.asm:PokerMinigame_TieText": "It's a tie.",
"poker_minigame.asm:PokerMinigame_WinDoubleUpText": "Yes!!",
"poker_minigame.asm:PokerMinigame_FailDoubleUpText": "Too bad...",
"poker_minigame.asm:PokerMinigame_AskBetText": "How many coins will you bet?",
"poker_minigame.asm:PokerMinigame_NotEnoughCoinsText": "Not enough coins!",
"poker_minigame.asm:PokerMinigame_PayoutText": "Yes!! Coins:",
"poker_minigame.asm:PokerMinigame_PayoutText#2": "won!",
"poker_minigame.asm:PokerMinigame_ShuffleCardsText": "Shuffling the cards.",
"poker_minigame.asm:PokerMinigame_DudText": "No win",
"poker_minigame.asm:PokerMinigame_OnePairText": "One Pair",
"poker_minigame.asm:PokerMinigame_TwoPairText": "Two Pair",
"poker_minigame.asm:PokerMinigame_ThreeOfAKindText": "Three of a Kind",
"poker_minigame.asm:PokerMinigame_StraightText": "Straight",
"poker_minigame.asm:PokerMinigame_FlushText": "Flush",
"poker_minigame.asm:PokerMinigame_FullHouseText": "Full House",
"poker_minigame.asm:PokerMinigame_StraightFlushText": "Straight Flush",
"poker_minigame.asm:PokerMinigame_FourOfAKindText": "Four of a Kind",
"poker_minigame.asm:PokerMinigame_FiveOfAKindText": "Five of a Kind",
"poker_minigame.asm:.text": "High / Low",
"poker_minigame.asm:.text#2": "10 coins / 5 coins / 1 coin",
"slot_machine_game.asm:.BetHowManyCoinsText": "How many coins will you bet?",
"slot_machine_game.asm:.SlotsStartText": "Start!",
"slot_machine_game.asm:.NotEnoughCoinsText": "Not enough coins!",
"slot_machine_game.asm:.MenuData": "3 coins / 2 coins / 1 coin",
"slot_machine_game.asm:.RanOutOfCoinsText": "You've run out of coins...",
"slot_machine_game.asm:.PlayAgainText": "Play one more round?",
"slot_machine_game.asm:.LinedUpText": "lined up! Coins:",
"slot_machine_game.asm:.LinedUpText#2": "won!",
"slot_machine_game.asm:.DarnText": "No win.",
# ---- debug menus ----------------------------------------------------------
"debug_menu.asm:.MenuData": "Fight / Field / Sound / Sub-game / Monster / Name",
"field_debug_menu_2.asm:.HealedText": "Restored the Pokémon's HP.",
"fight_debug_menu.asm:.FightTestText": "FIGHT TEST",
"fight_debug_menu.asm:.NumNameLevelText": "No.    NAME    LEVEL",
"fight_debug_menu.asm:.LayoutText": "1.▶000 -----  000 / 2. 000 -----  000 / 3. 000 -----  000 / 4. 000 -----  000 / 5. 000 -----  000 / 6. 000 -----  000",
"fight_debug_menu.asm:.LayoutText#2": "-----",
"fight_debug_menu.asm:.WildPokemonText": "WILD Pokémon",
"fight_debug_menu.asm:.TrainerText": "TRAINER",
"fight_debug_menu.asm:.EnemyNumNameLevelText": "No.    NAME        LEVEL",
"fight_debug_menu.asm:.EnemyNumNameLevelText#2": "000 ---------- 000",
"fight_debug_menu.asm:.PlayerNameText": "GOLD",
"subgame_debug_menu.asm:.MenuData": "Poker / 15 Puzzle / Memory / Picross / Slots",
# ---- debug/field ----------------------------------------------------------
"change_tileset.asm:.MenuData": "Cell 1 / Cell 2 / Cell 3",
"change_transportation.asm:.ChangeTransportationMenuData": "Walk / Bicycle / Skateboard / Lapras",
"change_transportation.asm:.PlayerTransportationString1": "<PLAYER> got off",
"change_transportation.asm:.PlayerTransportationString1#2": ".",
"change_transportation.asm:.PlayerTransportationString2": "<PLAYER> got on",
"change_transportation.asm:.PlayerTransportationString2#2": ".",
"change_transportation.asm:.CannotSurfString": "You can't ride here.",
"check_tile.asm:.HexadecimalNumbers": "0123456789ABCDEF",
"follow_npc_test.asm:.MenuData": "Start / End",
"follow_npc_test.asm:.CannotUseWithPokemonText": "Not allowed while a Pokémon is following you.",
"follow_npc_test.asm:.MenuData#2": "Pokémon walk-along / Follow-me demo / Rival's sister / In progress",
"item_test.asm:.CannotUsePCToolsText": "PC items can't be used.",
"item_test.asm:.ItemPickedText": "Picked an item!",
"item_test.asm:.UseOrTossMenuData": "USE / TOSS",
"item_test.asm:.TossConfirmText": "Throw it away? Are you sure?",
"item_test.asm:.ItemTossedText": "was tossed!",
"item_test.asm:.CannotTossText": "That's a very important item. It can't be tossed!",
"map_viewer.asm:.MapViewPrompt": "Use the Map Viewer?",
"map_viewer.asm:.ChangeViewerPrompt": "Cancel Viewer mode?",
"map_viewer.asm:.ActorCastText": "Actor Number / Cast Number",
"map_viewer.asm:.NoneText": "None",
"map_viewer.asm:.TableText": "Table",
"minigames.asm:.MenuData": "Slot Machine / Poker Game / Pair Game",
"minigames.asm:.MinigameConfirmationText": "Play it?",
"mon_following.asm:.MenuData": "Attach / Detach",
"mon_following.asm:.UnableText": "Not allowed!!",
"move_to_entrance.asm:.CantUseText": "Can't do that here. It can be run on Load 1.",
"move_to_entrance.asm:.MoveText": "Move to a specific point.",
"npc_movement_test.asm:.NotHereText": "Not allowed here!",
"pokemart_menu.asm:.MenuData": "Buy items / Sell items / Goodbye",
"pokemart_menu.asm:DebugMart_WelcomeText": "Welcome to the Friendly Shop!",
"pokemart_menu.asm:DebugMart_PokemartMenuText": "What can I do for you?",
"pokemart_menu.asm:DebugMart_GoodbyeText": "We hope to see you again.",
"pokemart_menu.asm:.BuyPromptText": "What would you like to buy?",
"pokemart_menu.asm:.HowManyText": "How many would you like?",
"pokemart_menu.asm:.ConfirmPurchaseText": "—",
"pokemart_menu.asm:.ConfirmPurchaseText#2": "at",
"pokemart_menu.asm:.ConfirmPurchaseText#3": "yen — will you buy them?",
"pokemart_menu.asm:.UnderDevelopmentText": "Sorry, this is under development.",
"pokemart_menu.asm:.CannotSellText": "That can't be used!",
"pokemart_menu.asm:.ImportantItemText": "That's an important item. It can't be sold!",
"pokemart_menu.asm:.NoItemsText": "You don't have a single item!",
"pokemart_menu.asm:.HowManyItemsText": "How many will you sell?",
"pokemart_menu.asm:.PlaceholderText": "Under development.",
"sprite_viewer.asm:.FollowPromptString": "Select this?",
"sprite_viewer.asm:.String": "Under development",
"field/teleport.asm:.MapRegisteredText": "This location was registered.",
"field/teleport.asm:.CannotRegisterMapText": "This place can't be registered!",
"toggle_npc_movement.asm:.MenuData": "Stop / Move",
"toolgear.asm:.MenuData": "Clock / Coords / Adjust / 60 sec / 24 hr / Clear",
"unused_flag_menu.asm:.MenuData": "Flag 1 / Flag 2 / Flag 3 / Flag 4",
"unused_priority_menu.asm:.MenuData": "Priority / Non-priority",
"vram_viewer.asm:.NoMapFlagsText": "This map has no sequence registered.",
"vram_viewer.asm:.MenuData": "Clear flags / Fill flags",
"warp.asm:.WarpToText": "Warping to it!",
# ---- misc / home ----------------------------------------------------------
"home/menu.asm:.MenuData": "YES / NO",
"names.asm:.TMText": "TM",
"names.asm:.HMText": "HM",
"print_hex.asm:.hexDigitTable": "0123456789ABCDEF",
"home/std_scripts.asm:.text": "I'll do better next time!!",
"talk_to_npc.asm:GameFreakText": "GAME FREAK!",
"text.asm:.Text": "ERROR",
}
